- src/errors.rs
- src/parser/bounds.rs
- src/parser/email.rs
- src/parser/extensions.rs
- src/parser/fix.rs
- src/parser/gpx.rs
- src/parser/link.rs
- src/parser/metadata.rs
- src/parser/mod.rs
- src/parser/person.rs
- src/parser/string.rs
- src/parser/time.rs
- src/parser/track.rs
- src/parser/tracksegment.rs
- src/parser/waypoint.rs
- src/reader.rs
- src/types.rs
Reworked every parser file, with the exception of extensions.rs.
Changes and cleanup were mostly:
- Every parser is now responsible for consuming his own starting and closing tags (previously some
parsers would be okay not having any starting tag, and would be used like this). To be able to achieve
this any parser that calls further consume functions must use peek() to leave starting tags in the reader
for the subparser to handle.
- Many parsers were accepting any amount of their starting tag, and also consuming any closing tag as
valid, ignoring the name. Now exactly one opening tag and matching closing tag is required.
- Parsers that were already using peek() were doing so via a level of indirection through some form of
"ParseEvent" enum, I think I have found a cleaner solution using …
> Rework parsing: More strict and (hopefully) cleaner

- src/parser/fix.rs
- src/parser/gpx.rs
- src/parser/link.rs
- src/parser/metadata.rs
- src/parser/mod.rs
- src/parser/person.rs
- src/parser/string.rs
- src/parser/time.rs
- src/parser/track.rs
- src/parser/waypoint.rs
Found an issue with a `.gpx` file, where the `"cmt"` and the `"desc"` fields for the waypoints were empty. It looks to me that is not a problem to have an empty comment or description. Looking at the spec, it just states that those fields must be strings (https://www.topografix.com/GPX/1/1/#type_wptType) , but there is no specification about if the have to be at least of length > 0.
My approach to fix it has been to modify the `string::consume` function, that accepts and additional bool parameter `allow_empty`. Another way would be to create a different function (`consume_opt` for example), that calls the original `consume` and checks the error. The problem with this approach is that I would need to check for the type of error returned from the `string::consume` function, and only if is …
> allow empty fields: "desc", "cmt", "description", "keywords", "src"

- src/parser/bounds.rs
- src/parser/email.rs
- src/parser/gpx.rs
- src/parser/link.rs
- src/parser/metadata.rs
- src/parser/person.rs
- src/parser/route.rs
- src/parser/string.rs
- src/parser/track.rs
- src/parser/tracksegment.rs
- src/parser/waypoint.rs
On my dummy benchmark (I parsed fuzzing corpus files) these optimizations improve performance total up to 23%.
There's two good performance increasing optimizations.
1. Remove cloning as much as possible (commit 816531ed67dc6d4b8fb53d1f8a80ca6008e2e57a). This gave up to 17% improvement. I'm not really familiar with `error-chain` so I probably did something silly there.
2.  Replace `.filter(p).nth(0)` with `.find(p)` from iterators (commit af771b8e6043af7d6d087f2581207bfd4c3228cb). This caught me by surprise, but showed up to 9% improvement. This was suggested by Clippy, so kudos to them!
> Some optimizations

- src/parser/gpx.rs
- src/types.rs
If we have a really simple gpx file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<gpx version="1.0" creator="https://github.com/georust/gpx">
<rte />
</gpx>
```
Before this PR, reading this file in gives us useless `Metadata` struct:
```
Gpx {
version: Gpx10,
metadata: Some(
Metadata {
name: None,
description: None,
author: Some(
Person {
name: None,
email: None,
link: None,
},
),
links: [],
time: None,
keywords: None,
bounds: None,
},
),
waypoints: [],
tracks: [],
route: Route {
name: None,
comment: None,
description: None,
source: None,
links: [],
number: None,
_type: None,
points: [],
},
}
```
and with this PR, when we read in the gpx the `metadata` is `None` as one might expect:
```
Gpx {
version: Gpx10,
metadata: None,
waypoints: [],
tracks: [],
route: Route {
name: None,
comment: …
```
> Only add Metadata to Gpx if there actually is metadata

- src/parser/gpx.rs
- src/types.rs
- src/writer.rs
- tests/gpx_read.rs
According to both GPX specifications 1.0 and 1.1, GPX file can have zero or more routes defined. This makes routes `Vec` like waypoints and tracks.
Fixes #34
> Add support for having multiple routes in GPX

- src/parser/waypoint.rs
- src/types.rs
- src/writer.rs
- tests/fixtures/with_accuracy.gpx
- tests/gpx_read.rs
- tests/gpx_write.rs
While there, change the Waypoint's age member to dgps_age to be more descriptive what it does.
I took the liberty to fix the [tests/fixtures/with_accuracy.gpx](https://github.com/georust/gpx/blob/master/tests/fixtures/with_accuracy.gpx) file to conform to specification and to fix the tests.
Fixes #21
> Rename "ageofgpsdata" field to "ageofdgpsdata"

- src/parser/gpx.rs
- src/types.rs
- src/writer.rs
The intent in GPX 1.1 specification is to
> include the name or URL of the software that created your GPX document. This allows others to inform the creator of a GPX instance document that fails to validate.
However, it is also used by some software to identify a device. For example by Strava (https://developers.strava.com/docs/uploads/):
> Device type is detected in all file types from standard ‘creator’ tags. These tags are then matched to a list of known devices. In some cases the name of the device will be displayed along with the activity details.
Fixes #40
> Add support for reading and writing of the GPX creator attribute

- .travis.yml
- src/parser/gpx.rs
- src/parser/mod.rs
- src/writer.rs
Travis builds are failing due to changes in rustfmt. I've updated the CI scripts following the guidance in https://github.com/rust-lang/rustfmt#on-the-nightly-toolchain.
> Update to the latest rustfmt

- CHANGELOG.md
- src/parser/gpx.rs
- src/parser/metadata.rs
- src/writer.rs
The description field of the metadata type is parsed and written with the "description" tag instead of "desc." I believe this is an error, as all other description fields in the crate follow the schema correctly for this field. This pull request resolves that discrepancy and should fix #48.
Schema reference: [1.0](https://www.topografix.com/gpx_manual.asp#desc)/[1.1](https://www.topografix.com/GPX/1/1/#type_metadataType)
> Use XML tag "desc" instead of "description"

- CHANGELOG.md
- src/parser/copyright.rs
- src/parser/metadata.rs
- src/parser/mod.rs
- src/types.rs
- tests/fixtures/strava_route_example.gpx
- tests/gpx_read.rs
This commit adds the GpxCopyright type and `parse/copyright.rs` which consumes the <copyright> tag of the metadata element.
I've also included a Strava route test case as well as some unit tests in the source file.
Fixes issue #45 
```
$ cargo test
test parser::copyright::tests::consume_barebones ... ok
test parser::copyright::tests::consume_simple_copyright ... ok
test gpx_reader_read_test_strava_route ... ok
```
> Support parsing copyright tag in metadata

- README.md
The old Travis CI badge seems outdated, so we could update the README to show the badge from github actions.
---
> Update ci badge in README

- CHANGELOG.md
- Cargo.toml
- src/parser/track.rs
- src/types.rs
- tests/fixtures/mousehole_to_paul.gpx
- tests/gpx_read.rs
GPX 1.1 Spec includes an optional Number on Track elements, which support is added for here.
Some Gpx files exported from google maps appear to include this so included test + test gpx file from that are used to verify change.
N.b. Number, as a u8, was already present and commented out on the Track struct - in case there was some history there being dragged up (It was already commented out during a refactor 4 years ago and that's as far back as i looked ...)
---
> Support Number on Tracks

- CHANGELOG.md
- src/lib.rs
- src/writer.rs
> Allow customize xml::writer::EventWriter in write

- CHANGELOG.md
- Cargo.toml
- src/types.rs
---
This PR resolves #59, by implementing optional support for (de-)serializing the GPX structs via serde.
I named the feature flag `serde-serialize`, same as in the `wasm-bindgen` crate.
Using `serde` for the feature flag name is not yet possible, since it would require the currently unstable [cargo namespaced features](https://doc.rust-lang.org/cargo/reference/unstable.html#namespaced-features) implementation.
See also the related [cargo tracking issue](https://github.com/rust-lang/cargo/issues/5565).
It was asked in #59, whether it would be possible to use GeoJSON, but for my usecase, it would be overkill to deal with additional data structure conversions.
I also checked the [Rust API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-serde), which mention …
> Implementing serde (De)Serialize for GPX structs

- CHANGELOG.md
- src/parser/route.rs
- tests/fixtures/viking_with_route_extensions.gpx
- tests/gpx_read.rs
The extensions tag is also allowed in the route tag (see https://www.topografix.com/GPX/1/1/#type_rteType).
> Do not crash if a gpx file has an extensions tag in its route tag

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- src/errors.rs
- src/parser/gpx.rs
- src/parser/metadata.rs
- src/parser/time.rs
- src/types.rs
- src/writer.rs
- tests/gpx_read.rs
> Allow to user chose chrono vs time

- CHANGELOG.md
- src/writer.rs
I noted that the exported GPX files are not accepted by Garmin software (for example Basecamp), and found out this is due to a missing namespace declaration. This PR adds the necessary `xmlns` tag to the `gpx` element.
---
> Add `xmlns` attribute in written gpx for better garmin compatibility

- CHANGELOG.md
- src/parser/waypoint.rs
- src/writer.rs
- tests/gpx_read.rs
> Address deprecation warnings

- CHANGELOG.md
- src/parser/waypoint.rs
> Waypoint name can be an empty string

- CHANGELOG.md
- src/parser/string.rs
- src/parser/waypoint.rs
- tests/fixtures/wahoo_example.gpx
- tests/gpx_read.rs
Similar to https://github.com/georust/gpx/issues/70, I have a GPX file that has self-closing `elevation` tags, which of course, contain no value. This appears to be valid per the GPX spec at https://www.topografix.com/GPX/1/1/#type_ptType.
The GPX file was generated by a Wahoo bike computer.
This change edits the parsing logic to use a default `f64` value of `0.00` for these cases. I didn't see a precedence for handling similar optional values in this lib, so let me know if I should handle this differently in accordance with the project's goals. 
---
> Allow empty elevation tags

- src/parser/time.rs
- src/types.rs
---
not sure if this is intentionally private, perhaps there is some other way to access time data from waypoints directly as chrono types? 
closes #75 if valid
> expose `Time`

- .github/workflows/test.yml
- CHANGELOG.md
---
Fixes build error:
https://github.com/georust/gpx/runs/7813032321?check_suite_focus=true
> error: package `time v0.3.13` cannot be built because it requires rustc 1.57.0 or newer, while the currently active rustc version is 1.56.1
> update MSRV to 1.57

- CHANGELOG.md
- Cargo.toml
- src/errors.rs
- src/parser/gpx.rs
- src/parser/time.rs
- src/parser/track.rs
- src/parser/waypoint.rs
- src/types.rs
- tests/fixtures/outdooractive-export.gpx
- tests/gpx_read.rs
- tests/gpx_write.rs
---
Implement changes proposed in https://github.com/georust/gpx/issues/77
I don't expect this to land directly as it adds a breaking change
> Switch from RFC3339 to ISO8601 for timestamp encoding

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- src/parser/bounds.rs
---
The previous two `geo-types` don't compile and `Coordinate` is deprecated, let's do a bit of Spring cleaning.
> Bump `geo-types` and use non-deprecated `Coord`

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
> Bump MSRV to 1.65

- Cargo.toml
---
This is soft-deprecated: https://rust-lang.github.io/rfcs/3052-optional-authors-field.html.
> Drop authors entry from manifest

- Cargo.toml
- src/parser/bounds.rs
---
Well, first of all, thanks again for the gpx crate! I've noticed the latest version parses gpx files that use some extensions without throwing an error, and I can access the time without going through a parse/format cycle, so it's even better now compared to last time I participated in this repo.
I'm not sure how valuable a changelog entry for this would be for users, and English is not my native language. So I haven't added one. Let me know if I should, or feel free to add it yourself if you want  :-)
I've noticed these deps do not appear to be needed. The error_chain dependency seems especially "wasteful" because it brings in a bunch of transitive dependencies. Commit messages:
---
Move `assert_approx_eq` crate to dev-dependencies
The crate is used in two test cases and appears not …
> Optimize deps: Drop `error_chain` and move `assert_approximate_eq` to dev-deps

- CHANGELOG.md
- src/parser/link.rs
---
I've sneaked in a second commit in this PR, to add a changelog entry for my previous PR that was merged without a changelog entry. After looking at the changelog, it seems like my previous decision to skip adding an entry was incorrect (the change probably was more important for users than CI rust version bumps).
Open question for this change: Should `<text></text>` result in `text = Some("")` or `text = None`? I like the current `Some("")` approach since I suspect some applications use this crate to read, change and then write GPX files. If `Some("")` was changed to `None` through some magic, the resulting GPX file would have the `<text></text>` removed. There would also be some (arguably mostly irrelevant) loss of information ("is there an empty text tag or no text tag?") when …
> Allow empty strings in `<text>` and `<type>` of `<link>`

- CHANGELOG.md
- src/parser/metadata.rs
---
I ran into an error while reading GPX files from [Sports Tracker](https://www.sports-tracker.com/). Those files appear to contain an empty name tag (`<name/>`) in the metadata that results in a `NoStringContent` error:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" creator="Sports Tracker" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd">
<metadata>
<name/>
<desc/>
<author><name>Jasper</name></author>
</metadata>
<trk>
<name/> …
```
> Allow empty name tag in metadata

- CHANGELOG.md
- src/writer.rs
---
Does what it says in the tin.
> Write speed to GPX 1.0 files

- .github/workflows/test.yml
---
rustup v1.28.0 included a breaking change to how command line arguments are parsed, see https://github.com/rust-lang/rustup/issues/4220 for more context.
> Fix CI for rustup v1.28.0 and later
